DROP TABLE IF EXISTS USERS; 
CREATE TABLE USERS (
	ID BIGINT NOT NULL,
	USERNAME VARCHAR(255) NOT NULL,
	PREFERENCES VARCHAR (10000) NOT NULL,
	CREATED DATETIME,
	LASTLOGIN DATETIME,
	PRIMARY KEY (ID)
);