DROP SEQUENCE IF EXISTS CUBUSMAIL_SEQ;
CREATE SEQUENCE CUBUSMAIL_SEQ START WITH 1000;


DROP TABLE IF EXISTS USERS; 
CREATE TABLE USERS (
	ID BIGINT PRIMARY KEY NOT NULL,
	USERNAME VARCHAR(255) NOT NULL,
	PREFERENCES VARCHAR(10000) NOT NULL,
	CREATED DATETIME,
	LASTLOGIN DATETIME
);	
CREATE UNIQUE INDEX INDEX_USERS1 ON USERS(USERNAME);


DROP TABLE IF EXISTS IDENTITIES; 
CREATE TABLE IDENTITIES
(
   ID BIGINT PRIMARY KEY NOT NULL,
   BCC VARCHAR(255),
   DISPLAYNAME VARCHAR(255),
   EMAIL VARCHAR(255),
   HTML_SIGNATURE BOOLEAN NOT NULL,
   ORGANIZATION VARCHAR(255),
   REPLY_TO VARCHAR(255),
   SIGNATURE VARCHAR(10000),
   STANDARD BOOLEAN NOT NULL,
   USER_ACCOUNT_ID BIGINT NOT NULL,
   FOREIGN KEY (USER_ACCOUNT_ID) REFERENCES USERS(ID) ON DELETE CASCADE
);


DROP TABLE IF EXISTS ADDRESSFOLDERS; 
CREATE TABLE ADDRESSFOLDERS
(
   ID BIGINT PRIMARY KEY NOT NULL,
   NAME VARCHAR(255) NOT NULL,
   TYPE INT NOT NULL,
   USER_ACCOUNT_ID BIGINT NOT NULL,
   FOREIGN KEY (USER_ACCOUNT_ID) REFERENCES USERS(ID) ON DELETE CASCADE
);


DROP TABLE IF EXISTS ADDRESSES; 
CREATE TABLE ADDRESSES
(
   ID BIGINT PRIMARY KEY NOT NULL,
   FIRSTNAME VARCHAR(128),
   MIDDLENAME VARCHAR(128),
   LASTNAME VARCHAR(128),
   TITLE VARCHAR(128),
   BIRTHDATE DATE,
   COMPANY VARCHAR(128),
   POSITION VARCHAR(128),
   DEPARTMENT VARCHAR(128),
   EMAIL VARCHAR(255),
   EMAIL2 VARCHAR(255),
   EMAIL3 VARCHAR(255),
   EMAIL4 VARCHAR(255),
   EMAIL5 VARCHAR(255),
   IM VARCHAR(255),
   URL VARCHAR(255),
   PRIVATEPHONE VARCHAR(128),
   WORKPHONE VARCHAR(128),
   PRIVATEMOBILE VARCHAR(128),
   WORKMOBILE VARCHAR(128),
   PRIVATEFAX VARCHAR(128),
   WORKFAX VARCHAR(128),
   PAGER VARCHAR(128),
   PRIVATESTREET VARCHAR(128),
   PRIVATEZIPCODE VARCHAR(128),
   PRIVATECITY VARCHAR(128),
   PRIVATESTATE VARCHAR(128),
   PRIVATECOUNTRY VARCHAR(128),
   WORKSTREET VARCHAR(128),
   WORKZIPCODE VARCHAR(128),
   WORKCITY VARCHAR(128),
   WORKSTATE VARCHAR(128),
   WORKCOUNTRY VARCHAR(128),
   NOTES VARCHAR(10000),
   ADDRESS_FOLDER_ID BIGINT NOT NULL,
   FOREIGN KEY (ADDRESS_FOLDER_ID) REFERENCES ADDRESSFOLDERS(ID) ON DELETE CASCADE
);  
