package com.cubusmail.smartgwt.client.mail;

import java.util.Date;

import com.cubusmail.smartgwt.client.ImageProvider;

public class MailData {
	private static MailRecord[] records;

	public static MailRecord[] getRecords() {
		if (records == null) {
			records = getNewRecords();
		}
		return records;
	}

	public static MailRecord[] getNewRecords() {
		return new MailRecord[] {
				new MailRecord(ImageProvider.MSG_NEW, "", "",
						"<b>Oliver Test</b>", "<b>Help from Support</b>",
						new Date(), 43243),
				new MailRecord(ImageProvider.MSG_NEW, "", "",
						"<b>Oliver Test</b>", "<b>Help from Support</b>",
						new Date(), 43243),
				new MailRecord(ImageProvider.MSG_STATUS_READ, "", "",
						"Oliver Test", "Help from Support", new Date(), 43243),
				new MailRecord(ImageProvider.MSG_STATUS_READ, "",
						ImageProvider.MSG_ATTACHMENT, "Oliver Test",
						"Help from Support", new Date(), 43243),
				new MailRecord(ImageProvider.MSG_STATUS_READ, "", "",
						"Oliver Test", "Help from Support", new Date(), 43243),
				new MailRecord(ImageProvider.MSG_STATUS_READ, "",
						ImageProvider.MSG_ATTACHMENT, "Oliver Test",
						"Help from Support", new Date(), 43243),
				new MailRecord(ImageProvider.MSG_STATUS_READ, "",
						ImageProvider.MSG_ATTACHMENT, "Oliver Test",
						"Help from Support", new Date(), 43243),
				new MailRecord(ImageProvider.MSG_STATUS_READ, "",
						ImageProvider.MSG_ATTACHMENT, "Oliver Test",
						"Help from Support", new Date(), 43243),
				new MailRecord(ImageProvider.MSG_STATUS_READ, "",
						ImageProvider.MSG_ATTACHMENT, "Oliver Test",
						"Help from Support", new Date(), 43243),
				new MailRecord(ImageProvider.MSG_STATUS_READ, "",
						ImageProvider.MSG_ATTACHMENT, "Oliver Test",
						"Help from Support", new Date(), 43243),
				new MailRecord(ImageProvider.MSG_STATUS_READ, "",
						ImageProvider.MSG_ATTACHMENT, "Oliver Test",
						"Help from Support", new Date(), 43243),
				new MailRecord(ImageProvider.MSG_STATUS_READ, "",
						ImageProvider.MSG_ATTACHMENT, "Oliver Test",
						"Help from Support", new Date(), 43243),
				new MailRecord(ImageProvider.MSG_STATUS_READ, "",
						ImageProvider.MSG_ATTACHMENT, "Oliver Test",
						"Help from Support", new Date(), 43243),
				new MailRecord(ImageProvider.MSG_STATUS_READ, "",
						ImageProvider.MSG_ATTACHMENT, "Oliver Test",
						"Help from Support", new Date(), 43243),
				new MailRecord(ImageProvider.MSG_STATUS_READ, "",
						ImageProvider.MSG_ATTACHMENT, "Oliver Test",
						"Help from Support", new Date(), 43243),
				new MailRecord(ImageProvider.MSG_STATUS_READ, "",
						ImageProvider.MSG_ATTACHMENT, "Oliver Test",
						"Help from Support", new Date(), 43243),
				new MailRecord(ImageProvider.MSG_STATUS_READ, "",
						ImageProvider.MSG_ATTACHMENT, "Oliver Test",
						"Help from Support", new Date(), 43243),
				new MailRecord(ImageProvider.MSG_STATUS_READ, "",
						ImageProvider.MSG_ATTACHMENT, "Oliver Test",
						"Help from Support", new Date(), 43243),
				new MailRecord(ImageProvider.MSG_STATUS_READ, "",
						ImageProvider.MSG_ATTACHMENT, "Oliver Test",
						"Help from Support", new Date(), 43243),
				new MailRecord(ImageProvider.MSG_STATUS_READ, "",
						ImageProvider.MSG_ATTACHMENT, "Oliver Test",
						"Help from Support", new Date(), 43243),
				new MailRecord(ImageProvider.MSG_STATUS_READ, "",
						ImageProvider.MSG_ATTACHMENT, "Oliver Test",
						"Help from Support", new Date(), 43243),
				new MailRecord(ImageProvider.MSG_STATUS_READ, "",
						ImageProvider.MSG_ATTACHMENT, "Oliver Test",
						"Help from Support", new Date(), 43243),
				new MailRecord(ImageProvider.MSG_STATUS_READ, "",
						ImageProvider.MSG_ATTACHMENT, "Oliver Test",
						"Help from Support", new Date(), 43243),
				new MailRecord(ImageProvider.MSG_STATUS_READ, "",
						ImageProvider.MSG_ATTACHMENT, "Oliver Test",
						"Help from Support", new Date(), 43243),
				new MailRecord(ImageProvider.MSG_STATUS_READ, "",
						ImageProvider.MSG_ATTACHMENT, "Oliver Test",
						"Help from Support", new Date(), 43243),
				new MailRecord(ImageProvider.MSG_STATUS_READ, "",
						ImageProvider.MSG_ATTACHMENT, "Oliver Test",
						"Help from Support", new Date(), 43243),
				new MailRecord(ImageProvider.MSG_STATUS_READ, "",
						ImageProvider.MSG_ATTACHMENT, "Oliver Test",
						"Help from Support", new Date(), 43243),
				new MailRecord(ImageProvider.MSG_STATUS_READ, "",
						ImageProvider.MSG_ATTACHMENT, "Oliver Test",
						"Help from Support", new Date(), 43243),
				new MailRecord(ImageProvider.MSG_STATUS_READ, "",
						ImageProvider.MSG_ATTACHMENT, "Oliver Test",
						"Help from Support", new Date(), 43243),
				new MailRecord(ImageProvider.MSG_STATUS_READ, "",
						ImageProvider.MSG_ATTACHMENT, "Oliver Test",
						"Help from Support", new Date(), 43243),
				new MailRecord(ImageProvider.MSG_STATUS_READ, "",
						ImageProvider.MSG_ATTACHMENT, "Oliver Test",
						"Help from Support", new Date(), 43243),
				new MailRecord(ImageProvider.MSG_STATUS_READ, "",
						ImageProvider.MSG_ATTACHMENT, "Oliver Test",
						"Help from Support", new Date(), 43243),
				new MailRecord(ImageProvider.MSG_STATUS_READ, "",
						ImageProvider.MSG_ATTACHMENT, "Oliver Test",
						"Help from Support", new Date(), 43243),
				new MailRecord(ImageProvider.MSG_STATUS_READ, "",
						ImageProvider.MSG_ATTACHMENT, "Oliver Test",
						"Help from Support", new Date(), 43243),
				new MailRecord(ImageProvider.MSG_STATUS_READ, "",
						ImageProvider.MSG_ATTACHMENT, "Oliver Test",
						"Help from Support", new Date(), 43243),
				new MailRecord(ImageProvider.MSG_STATUS_READ, "",
						ImageProvider.MSG_ATTACHMENT, "Oliver Test",
						"Help from Support", new Date(), 43243),
				new MailRecord(ImageProvider.MSG_STATUS_READ, "",
						ImageProvider.MSG_ATTACHMENT, "Oliver Test",
						"Help from Support", new Date(), 43243),
				new MailRecord(ImageProvider.MSG_STATUS_READ, "",
						ImageProvider.MSG_ATTACHMENT, "Oliver Test",
						"Help from Support", new Date(), 43243),
				new MailRecord(ImageProvider.MSG_STATUS_READ, "",
						ImageProvider.MSG_ATTACHMENT, "Oliver Test",
						"Help from Support", new Date(), 43243),
				new MailRecord(ImageProvider.MSG_STATUS_READ, "",
						ImageProvider.MSG_ATTACHMENT, "Oliver Test",
						"Help from Support", new Date(), 43243),
				new MailRecord(ImageProvider.MSG_STATUS_READ, "",
						ImageProvider.MSG_ATTACHMENT, "Oliver Test",
						"Help from Support", new Date(), 43243),
				new MailRecord(ImageProvider.MSG_STATUS_READ, "",
						ImageProvider.MSG_ATTACHMENT, "Oliver Test",
						"Help from Support", new Date(), 43243),
				new MailRecord(ImageProvider.MSG_STATUS_READ, "",
						ImageProvider.MSG_ATTACHMENT, "Oliver Test",
						"Help from Support", new Date(), 43243),
				new MailRecord(ImageProvider.MSG_STATUS_READ, "",
						ImageProvider.MSG_ATTACHMENT, "Oliver Test",
						"Help from Support", new Date(), 43243),
				new MailRecord(ImageProvider.MSG_STATUS_READ, "",
						ImageProvider.MSG_ATTACHMENT, "Oliver Test",
						"Help from Support", new Date(), 43243),
				new MailRecord(ImageProvider.MSG_STATUS_READ, "",
						ImageProvider.MSG_ATTACHMENT, "Oliver Test",
						"Help from Support", new Date(), 43243),
				new MailRecord(ImageProvider.MSG_STATUS_READ, "", "",
						"Oliver Test", "Help from Support", new Date(), 43243) };
	}

}
