DROP SEQUENCE IF EXISTS CUBUSMAIL_SEQ;
CREATE SEQUENCE CUBUSMAIL_SEQ START WITH 1000;


DROP TABLE IF EXISTS USERS; 
CREATE TABLE USERS (
	ID bigint PRIMARY KEY NOT NULL,
	USERNAME varchar(255) NOT NULL,
	PREFERENCES varchar(10000) NOT NULL,
	CREATED datetime,
	LASTLOGIN datetime
);	


DROP TABLE IF EXISTS IDENTITIES; 
CREATE TABLE IDENTITIES
(
   ID bigint PRIMARY KEY NOT NULL,
   BCC varchar(255),
   DISPLAYNAME varchar(255),
   EMAIL varchar(255),
   HTML_SIGNATURE boolean NOT NULL,
   ORGANIZATION varchar(255),
   REPLY_TO varchar(255),
   SIGNATURE varchar(10000),
   STANDARD boolean NOT NULL,
   USER_ACCOUNT_ID bigint,
   FOREIGN KEY (USER_ACCOUNT_ID) REFERENCES USERS(ID)
);


DROP TABLE IF EXISTS ADDRESSFOLDERS; 
CREATE TABLE ADDRESSFOLDERS
(
   ID bigint PRIMARY KEY NOT NULL,
   NAME varchar(255),
   TYPE integer,
   USER_ACCOUNT_ID bigint,
   FOREIGN KEY (USER_ACCOUNT_ID) REFERENCES USERS(ID)
);


DROP TABLE IF EXISTS ADDRESSES; 
CREATE TABLE ADDRESSES
(
   ID bigint PRIMARY KEY NOT NULL,
   ADDRESS_FOLDER_ID bigint,
   FOREIGN KEY (ADDRESS_FOLDER_ID) REFERENCES ADDRESSFOLDERS(ID)
);
