
CREATE SEQUENCE IF NOT EXISTS CUBUSMAIL_SEQ START WITH 16926;


DROP TABLE IF EXISTS USERS; 
CREATE TABLE USERS (
	ID bigint PRIMARY KEY NOT NULL,
	USERNAME varchar(255) NOT NULL,
	PREFERENCES varchar(10000) NOT NULL,
	CREATED datetime,
	LASTLOGIN datetime,
);
CREATE UNIQUE INDEX PRIMARY_KEY_USERS1 ON USERS(ID);
CREATE UNIQUE INDEX PRIMARY_KEY_USERS2 ON USERS(USERNAME);


CREATE TABLE IDENTITIES
(
   ID bigint PRIMARY KEY NOT NULL,
   BCC varchar(255),
   DISPLAYNAME varchar(255),
   EMAIL varchar(255),
   HTMLSIGNATURE boolean NOT NULL,
   ORGANISATION varchar(255),
   REPLYTO varchar(255),
   SIGNATURE varchar(10000),
   STANDARD boolean NOT NULL,
   USERS_FK bigint
);
CREATE UNIQUE INDEX PRIMARY_KEY_IDENTITIES1 ON IDENTITIES(ID);
CREATE UNIQUE INDEX PRIMARY_KEY_IDENTITIES2 ON IDENTITIES(USERS_FK);
