CREATE SEQUENCE IF NOT EXISTS CUBUSMAIL_SEQ START WITH 16926;

DROP TABLE IF EXISTS USERS; 
CREATE TABLE USERS (
	ID BIGINT NOT NULL AUTO_INCREMENT,
	USERNAME VARCHAR(255) NOT NULL,
	PREFERENCES VARCHAR (10000) NOT NULL,
	CREATED DATETIME,
	LASTLOGIN DATETIME,
	PRIMARY KEY (ID)
);